
package com.hotjoe.services.test.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HeartBeatServiceService", targetNamespace = "http://ws.services.hotjoe.com/", wsdlLocation = "http://localhost:8080/sample/HeartBeatService?wsdl")
public class HeartBeatServiceService
    extends Service
{

    private final static URL HEARTBEATSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException HEARTBEATSERVICESERVICE_EXCEPTION;
    private final static QName HEARTBEATSERVICESERVICE_QNAME = new QName("http://ws.services.hotjoe.com/", "HeartBeatServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sample/HeartBeatService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HEARTBEATSERVICESERVICE_WSDL_LOCATION = url;
        HEARTBEATSERVICESERVICE_EXCEPTION = e;
    }

    public HeartBeatServiceService() {
        super(__getWsdlLocation(), HEARTBEATSERVICESERVICE_QNAME);
    }

    public HeartBeatServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HEARTBEATSERVICESERVICE_QNAME, features);
    }

    public HeartBeatServiceService(URL wsdlLocation) {
        super(wsdlLocation, HEARTBEATSERVICESERVICE_QNAME);
    }

    public HeartBeatServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HEARTBEATSERVICESERVICE_QNAME, features);
    }

    public HeartBeatServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HeartBeatServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HeartBeatService
     */
    @WebEndpoint(name = "HeartBeatServicePort")
    public HeartBeatService getHeartBeatServicePort() {
        return super.getPort(new QName("http://ws.services.hotjoe.com/", "HeartBeatServicePort"), HeartBeatService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HeartBeatService
     */
    @WebEndpoint(name = "HeartBeatServicePort")
    public HeartBeatService getHeartBeatServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.services.hotjoe.com/", "HeartBeatServicePort"), HeartBeatService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HEARTBEATSERVICESERVICE_EXCEPTION!= null) {
            throw HEARTBEATSERVICESERVICE_EXCEPTION;
        }
        return HEARTBEATSERVICESERVICE_WSDL_LOCATION;
    }

}
