
package com.hotjoe.services.test.ws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ProductAlreadyExistsException", targetNamespace = "http://ws.services.hotjoe.com/")
public class ProductAlreadyExistsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ProductAlreadyExistsException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ProductAlreadyExistsException_Exception(String message, ProductAlreadyExistsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ProductAlreadyExistsException_Exception(String message, ProductAlreadyExistsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.hotjoe.services.test.ws.client.ProductAlreadyExistsException
     */
    public ProductAlreadyExistsException getFaultInfo() {
        return faultInfo;
    }

}
