
package com.hotjoe.services.test.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://ws.services.hotjoe.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.hotjoe.services.test.ws.client.Product
     * @throws ProductNotFoundException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Product getProduct(
        @WebParam(name = "arg0", partName = "arg0")
        GetProductRequest arg0)
        throws ProductNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.hotjoe.services.test.ws.client.Product
     * @throws ProductAlreadyExistsException_Exception
     * @throws BadProductNameException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Product createProduct(
        @WebParam(name = "arg0", partName = "arg0")
        Product arg0)
        throws BadProductNameException_Exception, ProductAlreadyExistsException_Exception
    ;

}
