
package com.hotjoe.services.test.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VersionService", targetNamespace = "http://ws.services.hotjoe.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VersionService {


    /**
     * 
     * @return
     *     returns com.hotjoe.services.test.ws.client.VersionInfo
     * @throws VersionFileNotFoundException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public VersionInfo getFullStatus()
        throws VersionFileNotFoundException_Exception
    ;

}
