
package com.hotjoe.services.test.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VersionServiceService", targetNamespace = "http://ws.services.hotjoe.com/", wsdlLocation = "http://localhost:8080/sample/VersionService?wsdl")
public class VersionServiceService
    extends Service
{

    private final static URL VERSIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException VERSIONSERVICESERVICE_EXCEPTION;
    private final static QName VERSIONSERVICESERVICE_QNAME = new QName("http://ws.services.hotjoe.com/", "VersionServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sample/VersionService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VERSIONSERVICESERVICE_WSDL_LOCATION = url;
        VERSIONSERVICESERVICE_EXCEPTION = e;
    }

    public VersionServiceService() {
        super(__getWsdlLocation(), VERSIONSERVICESERVICE_QNAME);
    }

    public VersionServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VERSIONSERVICESERVICE_QNAME, features);
    }

    public VersionServiceService(URL wsdlLocation) {
        super(wsdlLocation, VERSIONSERVICESERVICE_QNAME);
    }

    public VersionServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VERSIONSERVICESERVICE_QNAME, features);
    }

    public VersionServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VersionServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VersionService
     */
    @WebEndpoint(name = "VersionServicePort")
    public VersionService getVersionServicePort() {
        return super.getPort(new QName("http://ws.services.hotjoe.com/", "VersionServicePort"), VersionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VersionService
     */
    @WebEndpoint(name = "VersionServicePort")
    public VersionService getVersionServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.services.hotjoe.com/", "VersionServicePort"), VersionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VERSIONSERVICESERVICE_EXCEPTION!= null) {
            throw VERSIONSERVICESERVICE_EXCEPTION;
        }
        return VERSIONSERVICESERVICE_WSDL_LOCATION;
    }

}
